export default constants = {
    headerHeight: 70,
    red_types: {
        set_user: 'set_username',
        set_pass: 'set_password',
        set_login: 'set_login_status',
        set_error: 'set_error',
        set_loader_size: 'set_loader_size',
        set_loader_visibility: 'set_loader_visibility',
        reset_login: 'reset_login',
        set_devices_model: 'set_devices_model',
        logout: 'set_logout',
        set_device_data: 'set_device_data',
        set_current_device: 'set_current_device',
        set_current_device_id: 'set_current_device_id',
        reset_device: 'reset_device',
        set_date: 'set_date',
        set_picekr: 'set_picker',
        reset_history: 'reset_history',
        set_history_day_data: 'set_history_day_data',
        set_week: 'set_week',
        set_notifications: 'set_notifications',
        update_notifications: 'update_notifications',
        set_login_or_signup_cross_action: 'set_login_or_signup_cross_action'
    },
}